{
  BMFont
  Part of Posit-92 game engine
  By Hevanafa
}

unit P92BMFont;

{$Mode ObjFPC}
{$H-}  { Use ShortStrings }
{$J-}  { Don't allow assignments to typed consts }

interface

uses P92AssetHandles;

type
  TByteRange = 0..255;

  PBMFontGlyph = ^TBMFontGlyph;
  TBMFontGlyph = record
    id: word;
    x, y, width, height: word;
    xoffset, yoffset: smallint;
    xadvance: smallint;
  end;

  PBMFont = ^TBMFont;
  TBMFont = record
    texHandle: longint;
    lineHeight: smallint;
    spacing: array[0..1] of byte;
    glyphs: array[TByteRange] of TBMFontGlyph;
  end;


function CloneBMFont(const srcFontHandle: TBMFontHandle): TBMFontHandle;
procedure FreeBMFont(const fontHandle: TBMFontHandle);

procedure PrintBMFont(
  const fontHandle: TBMFontHandle;
  const text: string;
  const x, y: smallint);

function MeasureBMFont(
  const fontHandle: TBMFontHandle;
  const text: string): smallint;

function PrintBMFontCharColour(
  const fontHandle: TBMFontHandle;
  const ch: char;
  const x, y: smallint;
  const colour: longword): word;

procedure PrintBMFontColour(
  const fontHandle: TBMFontHandle;
  const text: string;
  const x, y: smallint;
  const colour: longword);

function PrintBMFontCharToDest(
  const fontHandle: TBMFontHandle;
  const destHandle: longint;
  const ch: char;
  const x, y: smallint): smallint;

procedure PrintBMFontToDest(
  const fontHandle: TBMFontHandle;
  const destHandle: longint;
  const text: string;
  const x, y: smallint);


implementation

uses
  P92Conversions, P92Logger, P92AssetRegistry, P92PanicDisplay,
  P92Tex, P92TexDraw;

{ Returns glyph.xadvance }
function PrintBMFontChar(
  const fontHandle: TBMFontHandle;
  const ch: char;
  const x, y: smallint): smallint;
var
  fontPtr: PBMFont;
  charcode: byte;
  glyphIdx: smallint;
  glyph: TBMFontGlyph;
begin
  fontPtr := BorrowBMFontPtr(fontHandle);

  charcode := ord(ch);
  glyphIdx := charcode;

  if (glyphIdx in [low(fontPtr^.glyphs)..high(fontPtr^.glyphs)]) then begin
    glyph := fontPtr^.glyphs[glyphIdx];

    SprRegion(
      fontPtr^.texHandle,
      glyph.x, glyph.y,
      glyph.width, glyph.height,
      x + glyph.xoffset, y + glyph.yoffset);
    
    PrintBMFontChar := glyph.xadvance
  end else
    PrintBMFontChar := 0;
end;

function CloneBMFont(const srcFontHandle: TBMFontHandle): TBMFontHandle;
var
  destFontHandle: TBMFontHandle;
begin
  destFontHandle := FindUnusedBMFontHandle;

  if destFontHandle < 0 then
    PanicHaltDisplay('BMFont handles are full!');

  bmfonts[destFontHandle] := bmfonts[srcFontHandle];
  bmfonts[destFontHandle].font.texHandle := CopyTexture(bmfonts[srcFontHandle].font.texHandle);

  CloneBMFont := destFontHandle
end;

procedure FreeBMFont(const fontHandle: TBMFontHandle);
var
  a: word;
begin
  bmfonts[fontHandle].status := AssetStatusEmpty;
  bmfonts[fontHandle].errorCode := 0;

  fillchar(bmfonts[fontHandle].font, sizeof(TBMFont), 0);

  for a:=0 to high(bmfonts[fontHandle].font.glyphs) do
    fillchar(bmfonts[fontHandle].font.glyphs[a], sizeof(TBMFontGlyph), 0);

  FreeTexture(BorrowBMFontPtr(fontHandle)^.texHandle)
end;

procedure PrintBMFont(
  const fontHandle: TBMFontHandle;
  const text: string;
  const x, y: smallint);
var
  fontPtr: PBMFont;
  a: word;
  ch: char;
  left, step: smallint;
begin
  fontPtr := BorrowBMFontPtr(fontHandle);
  left := 0;

  for a:=1 to length(text) do begin
    ch := text[a];
    step := PrintBMFontChar(fontHandle, ch, x + left, y);

    if a < length(text) then
      inc(left, step + fontPtr^.spacing[0])
    else
      inc(left, step);
  end;
end;


function MeasureBMFont(
  const fontHandle: TBMFontHandle;
  const text: string): smallint;
var
  fontPtr: PBMFont;
  a: word;
  glyphIdx: smallint;
  charcode: byte;
begin
  fontPtr := BorrowBMFontPtr(fontHandle);
  MeasureBMFont := 0;

  for a:=1 to length(text) do begin
    charcode := ord(text[a]);

    glyphIdx := charcode;

    if (glyphIdx in [low(fontPtr^.glyphs)..high(fontPtr^.glyphs)]) then begin
      if a < length(text) then
        inc(MeasureBMFont, fontPtr^.glyphs[glyphIdx].xadvance + fontPtr^.spacing[0])
      else
        inc(MeasureBMFont, fontPtr^.glyphs[glyphIdx].xadvance);
    end;
  end;
end;

{ Returns xadvance for the next char }
function PrintBMFontCharColour(
  const fontHandle: TBMFontHandle;
  const ch: char;
  const x, y: smallint;
  const colour: longword): word;
var
  fontPtr: PBMFont;
  charcode: byte;
  glyphIdx: smallint;
  glyph: TBMFontGlyph;
begin
  fontPtr := BorrowBMFontPtr(fontHandle);
  charcode := ord(ch);
  glyphIdx := charcode;

  PrintBMFontCharColour := 0;

  if (glyphIdx in [low(fontPtr^.glyphs)..high(fontPtr^.glyphs)]) then begin
    glyph := fontPtr^.glyphs[glyphIdx];

    SprRegionSolid(
      fontPtr^.texHandle,
      glyph.x, glyph.y,
      glyph.width, glyph.height,
      x + glyph.xoffset, y + glyph.yoffset,
      colour);

    PrintBMFontCharColour := glyph.xadvance
  end;
end;

procedure PrintBMFontColour(
  const fontHandle: TBMFontHandle;
  const text: string;
  const x, y: smallint;
  const colour: longword);
var
  a: word;
  left, step: smallint;
begin
  left := 0;

  for a:=1 to length(text) do begin
    step := PrintBMFontCharColour(
        fontHandle,
        text[a],
        x + left, y,
        colour);

    if a < length(text) then
      inc(left, step + BorrowBMFontPtr(fontHandle)^.spacing[0])
    else
      inc(left, step);
  end;
end;


function PrintBMFontCharToDest(
  const fontHandle: TBMFontHandle;
  const destHandle: longint;
  const ch: char;
  const x, y: smallint): smallint;
var
  fontPtr: PBMFont;
  charcode: byte;
  glyphIdx: smallint;
  glyph: TBMFontGlyph;
begin
  PrintBMFontCharToDest := 0;
  fontPtr := BorrowBMFontPtr(fontHandle);

  if not IsTextureSet(destHandle) then exit;

  charcode := ord(ch);

  glyphIdx := charcode;

  if (glyphIdx in [low(fontPtr^.glyphs)..high(fontPtr^.glyphs)]) then begin
    glyph := fontPtr^.glyphs[glyphIdx];

    SprRegionToDest(
      fontPtr^.texHandle,
      destHandle,
      glyph.x, glyph.y,
      glyph.width, glyph.height,
      x + glyph.xoffset, y + glyph.yoffset);
    
    PrintBMFontCharToDest := glyph.xadvance
  end else
    PrintBMFontCharToDest := 0;
end;

procedure PrintBMFontToDest(
  const fontHandle: TBMFontHandle;
  const destHandle: longint;
  const text: string;
  const x, y: smallint);
var
  a: word;
  ch: char;
  left, step: smallint;
begin
  left := 0;

  for a:=1 to length(text) do begin
    ch := text[a];
    step := PrintBMFontCharToDest(fontHandle, destHandle, ch, x + left, y);

    if a < length(text) then
      inc(left, step + BorrowBMFontPtr(fontHandle)^.spacing[0])
    else
      inc(left, step);
  end;
end;

end.
