{
  Common conversion utility unit - Part of Posit-92 game engine
  Hevanafa
}

unit Conv;

{$Mode ObjFPC}
{$H-}{$J+}

interface

function i32str(const value: Longint): string;
function f32str(const value: double): string;
function toFixed(const value: double; const decimals: smallint): string;
function i16HexStr(const value: word): string;
function i8HexStr(const value: byte): string;
function boolStr(const value: boolean): string;
function parseInt(const text: string): smallint;

function strPtrToString(const strPtr: PByte; const strLen: byte): ShortString;


implementation

function i32str(const value: longInt): string;
begin
  str(value, i32str)
end;

function f32str(const value: double): string;
begin
  str(value:0:4, f32str)
end;

function toFixed(const value: double; const decimals: smallint): string;
begin
  str(value:0:decimals, toFixed)
end;



function i16HexStr(const value: word): string;
const
  digits: array[0..15] of char = '0123456789ABCDEF';
var
  a: byte;
begin
  i16HexStr := '';
  for a := 3 downto 0 do
    i16HexStr := i16HexStr + digits[(value shr (a * 4)) and $F];
end;

function i8HexStr(const value: byte): string;
const
  digits: array[0..15] of char = '0123456789ABCDEF';
begin
  i8HexStr := digits[(value shr 4) and $F] + digits[value and $F];
end;

function boolStr(const value: boolean): string;
begin
  if value then
    boolStr := 'true'
  else
    boolStr := 'false'
end;

function parseInt(const text: string): smallint;
var
  parseResult: smallint;
begin
  val(text, parseInt, parseResult);

  if parseResult <> 0 then begin
    writeLn('Error parsing to smallint:', text);
    parseInt := 0
  end;
end;


function strPtrToString(const strPtr: PByte; const strLen: byte): ShortString;
var
  text: string;
  a: smallint;
  charPtr: ^byte;
begin
  setLength(text, strLen);
  charPtr := strPtr;
  for a:=1 to strLen do begin
    text[a] := char(charPtr^);
    inc(charPtr)
  end;

  strPtrToString := text
end;


end.
