{
  FPS unit - Part of Posit-92 game engine
  Hevanafa

  Mandatory for FPS (frames per second) counting
}

unit FPS;

{$Mode ObjFPC}
{$H+}{$J-}

interface

procedure initFPSCounter;
procedure incrementFPS;

function getLastFPS: smallint;


implementation

uses
  Conv, Timing, VGA;

var
  actualFPS, lastFPS: smallint;
  lastFPSTime: double; { in seconds }

procedure initFPSCounter;
begin
  actualFPS := 0;
  lastFPS := 0;
  lastFPSTime := getTimer;
end;

procedure incrementFPS;
begin
  actualFPS := actualFPS + 1;
  if getTimer - lastFPSTime >= 1.0 then begin
    lastFPSTime := getTimer;
    lastFPS := actualFPS;
    actualFPS := 1
  end;
end;

function getLastFPS: smallint;
begin
  getLastFPS := lastFPS
end;


end.
